name: Release - Build & Deploy

on:
  # Triggers the workflow on push or pull request events but only for dev branch
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read docker properties
        uses: madhead/read-java-properties@latest
        id: docker
        with:
          file: docker.properties
          all: true
      - name: setup java sdk 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          server-id: sonatype-nexus-snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - id: install-secret-key
        name: install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: build with maven
        run: mvn --file pom.xml clean install package

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build and push to docker hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            zesticio/pim:latest
            zesticio/pim:${{ steps.docker.outputs.MAJOR_VERSION }}.${{ steps.docker.outputs.MINOR_VERSION }}.${{ steps.buildnumber.outputs.build_number }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}